import { MenuItem, MenuCategory } from './store';

// فئات القائمة
export const menuCategories: MenuCategory[] = [
  { id: 'cat-1', name: 'المقبلات', nameEn: 'Appetizers', icon: '🥗', sortOrder: 1, isActive: true },
  { id: 'cat-2', name: 'الأطباق الرئيسية', nameEn: 'Main Dishes', icon: '🍖', sortOrder: 2, isActive: true },
  { id: 'cat-3', name: 'المشويات', nameEn: 'Grills', icon: '🔥', sortOrder: 3, isActive: true },
  { id: 'cat-4', name: 'الأرز والمعكرونة', nameEn: 'Rice & Pasta', icon: '🍚', sortOrder: 4, isActive: true },
  { id: 'cat-5', name: 'الشوربة', nameEn: 'Soups', icon: '🍲', sortOrder: 5, isActive: true },
  { id: 'cat-6', name: 'السلطات', nameEn: 'Salads', icon: '🥬', sortOrder: 6, isActive: true },
  { id: 'cat-7', name: 'المشروبات', nameEn: 'Beverages', icon: '🥤', sortOrder: 7, isActive: true },
  { id: 'cat-8', name: 'الحلويات', nameEn: 'Desserts', icon: '🍰', sortOrder: 8, isActive: true },
  { id: 'cat-9', name: 'وجبات الأطفال', nameEn: 'Kids Menu', icon: '🧒', sortOrder: 9, isActive: true },
];

// عناصر القائمة
export const menuItems: MenuItem[] = [
  // المقبلات
  {
    id: 'item-1',
    categoryId: 'cat-1',
    name: 'حمص بالطحينة',
    nameEn: 'Hummus',
    description: 'حمص مهروس مع طحينة وزيت زيتون وليمون',
    price: 45,
    isAvailable: true,
    preparationTime: 5,
    calories: 180,
    allergens: ['سمسم'],
  },
  {
    id: 'item-2',
    categoryId: 'cat-1',
    name: 'بابا غنوج',
    nameEn: 'Baba Ghanoush',
    description: 'باذنجان مشوي مع طحينة وثوم',
    price: 50,
    isAvailable: true,
    preparationTime: 7,
    calories: 150,
    allergens: ['سمسم'],
  },
  {
    id: 'item-3',
    categoryId: 'cat-1',
    name: 'ورق عنب',
    nameEn: 'Stuffed Grape Leaves',
    description: 'ورق عنب محشي بالأرز والتوابل',
    price: 65,
    isAvailable: true,
    preparationTime: 5,
    calories: 200,
  },
  {
    id: 'item-4',
    categoryId: 'cat-1',
    name: 'فتة بالسمنة',
    nameEn: 'Fattah',
    description: 'خبز مقرمش مع لحم وأرز ومرق',
    price: 85,
    isAvailable: true,
    preparationTime: 10,
    calories: 450,
  },
  
  // الأطباق الرئيسية
  {
    id: 'item-5',
    categoryId: 'cat-2',
    name: 'كشري مصري',
    nameEn: 'Egyptian Koshari',
    description: 'أرز ومعكرونة وعدس مع صلصة الطماطم',
    price: 55,
    isAvailable: true,
    preparationTime: 10,
    calories: 550,
  },
  {
    id: 'item-6',
    categoryId: 'cat-2',
    name: 'ملوخية بالأرانب',
    nameEn: 'Molokhia with Rabbit',
    description: 'ملوخية طازجة مع لحم الأرانب',
    price: 180,
    isAvailable: true,
    preparationTime: 25,
    calories: 380,
  },
  {
    id: 'item-7',
    categoryId: 'cat-2',
    name: 'فتة لحم',
    nameEn: 'Meat Fattah',
    description: 'فتة باللحم الضاني مع الأرز والخل',
    price: 145,
    isAvailable: true,
    preparationTime: 20,
    calories: 620,
  },
  {
    id: 'item-8',
    categoryId: 'cat-2',
    name: 'طاجن لسان عصفور',
    nameEn: 'Orzo Tagine',
    description: 'لسان عصفور مع اللحم والتوابل',
    price: 120,
    isAvailable: true,
    preparationTime: 30,
    calories: 480,
  },
  
  // المشويات
  {
    id: 'item-9',
    categoryId: 'cat-3',
    name: 'كباب مشكل',
    nameEn: 'Mixed Kebab',
    description: 'تشكيلة من الكباب واللحم المفروم',
    price: 185,
    isAvailable: true,
    preparationTime: 20,
    calories: 550,
  },
  {
    id: 'item-10',
    categoryId: 'cat-3',
    name: 'شيش طاووق',
    nameEn: 'Shish Tawook',
    description: 'دجاج متبل مشوي على الفحم',
    price: 145,
    isAvailable: true,
    preparationTime: 18,
    calories: 380,
  },
  {
    id: 'item-11',
    categoryId: 'cat-3',
    name: 'كفتة مشوية',
    nameEn: 'Grilled Kofta',
    description: 'كفتة لحم مشوية مع البهارات',
    price: 135,
    isAvailable: true,
    preparationTime: 15,
    calories: 420,
  },
  {
    id: 'item-12',
    categoryId: 'cat-3',
    name: 'ريش ضاني',
    nameEn: 'Lamb Chops',
    description: 'ريش ضاني مشوية مع الأعشاب',
    price: 280,
    isAvailable: true,
    preparationTime: 25,
    calories: 650,
  },
  
  // الأرز والمعكرونة
  {
    id: 'item-13',
    categoryId: 'cat-4',
    name: 'أرز بالخلطة',
    nameEn: 'Rice with Mixed Nuts',
    description: 'أرز مع كبد ومكسرات',
    price: 75,
    isAvailable: true,
    preparationTime: 15,
    calories: 380,
  },
  {
    id: 'item-14',
    categoryId: 'cat-4',
    name: 'مكرونة بشاميل',
    nameEn: 'Béchamel Pasta',
    description: 'مكرونة بالبشاميل واللحم المفروم',
    price: 95,
    isAvailable: true,
    preparationTime: 20,
    calories: 580,
  },
  
  // الشوربة
  {
    id: 'item-15',
    categoryId: 'cat-5',
    name: 'شوربة لسان عصفور',
    nameEn: 'Orzo Soup',
    description: 'شوربة دجاج مع لسان العصفور',
    price: 40,
    isAvailable: true,
    preparationTime: 8,
    calories: 150,
  },
  {
    id: 'item-16',
    categoryId: 'cat-5',
    name: 'شوربة عدس',
    nameEn: 'Lentil Soup',
    description: 'شوربة عدس أصفر مع الليمون',
    price: 35,
    isAvailable: true,
    preparationTime: 5,
    calories: 180,
  },
  
  // السلطات
  {
    id: 'item-17',
    categoryId: 'cat-6',
    name: 'سلطة خضراء',
    nameEn: 'Green Salad',
    description: 'خس وخيار وطماطم مع صوص الليمون',
    price: 35,
    isAvailable: true,
    preparationTime: 5,
    calories: 80,
  },
  {
    id: 'item-18',
    categoryId: 'cat-6',
    name: 'تبولة',
    nameEn: 'Tabbouleh',
    description: 'بقدونس مع برغل وطماطم ونعناع',
    price: 45,
    isAvailable: true,
    preparationTime: 7,
    calories: 120,
  },
  {
    id: 'item-19',
    categoryId: 'cat-6',
    name: 'فتوش',
    nameEn: 'Fattoush',
    description: 'سلطة بالخبز المحمص وصوص الرمان',
    price: 50,
    isAvailable: true,
    preparationTime: 8,
    calories: 140,
  },
  
  // المشروبات
  {
    id: 'item-20',
    categoryId: 'cat-7',
    name: 'عصير مانجو',
    nameEn: 'Mango Juice',
    description: 'عصير مانجو طازج',
    price: 30,
    isAvailable: true,
    preparationTime: 3,
    calories: 120,
  },
  {
    id: 'item-21',
    categoryId: 'cat-7',
    name: 'عصير قصب',
    nameEn: 'Sugarcane Juice',
    description: 'عصير قصب طازج',
    price: 25,
    isAvailable: true,
    preparationTime: 5,
    calories: 180,
  },
  {
    id: 'item-22',
    categoryId: 'cat-7',
    name: 'شاي بالنعناع',
    nameEn: 'Mint Tea',
    description: 'شاي أحمر مع نعناع طازج',
    price: 15,
    isAvailable: true,
    preparationTime: 3,
    calories: 5,
  },
  {
    id: 'item-23',
    categoryId: 'cat-7',
    name: 'قهوة تركي',
    nameEn: 'Turkish Coffee',
    description: 'قهوة تركي أصلية',
    price: 20,
    isAvailable: true,
    preparationTime: 5,
    calories: 10,
  },
  
  // الحلويات
  {
    id: 'item-24',
    categoryId: 'cat-8',
    name: 'أم علي',
    nameEn: 'Om Ali',
    description: 'حلوى مصرية بالمكسرات والقشطة',
    price: 55,
    isAvailable: true,
    preparationTime: 10,
    calories: 450,
    allergens: ['حليب', 'مكسرات'],
  },
  {
    id: 'item-25',
    categoryId: 'cat-8',
    name: 'بسبوسة',
    nameEn: 'Basbousa',
    description: 'كيك السميد بالقطر',
    price: 35,
    isAvailable: true,
    preparationTime: 5,
    calories: 280,
    allergens: ['حليب'],
  },
  {
    id: 'item-26',
    categoryId: 'cat-8',
    name: 'كنافة بالقشطة',
    nameEn: 'Kunafa',
    description: 'كنافة مقرمشة بالقشطة والفستق',
    price: 65,
    isAvailable: true,
    preparationTime: 8,
    calories: 380,
    allergens: ['حليب', 'مكسرات'],
  },
  
  // وجبات الأطفال
  {
    id: 'item-27',
    categoryId: 'cat-9',
    name: 'ناجتس دجاج',
    nameEn: 'Chicken Nuggets',
    description: 'قطع دجاج مقلية مع بطاطس',
    price: 65,
    isAvailable: true,
    preparationTime: 12,
    calories: 420,
  },
  {
    id: 'item-28',
    categoryId: 'cat-9',
    name: 'برجر صغير',
    nameEn: 'Mini Burger',
    description: 'برجر لحم صغير مع جبنة',
    price: 55,
    isAvailable: true,
    preparationTime: 10,
    calories: 380,
    allergens: ['حليب', 'جلوتين'],
  },
];

// بيانات الطاولات
export const tables = [
  { id: 'table-1', number: 1, seats: 2, zone: 'داخلي', status: 'available' as const },
  { id: 'table-2', number: 2, seats: 2, zone: 'داخلي', status: 'available' as const },
  { id: 'table-3', number: 3, seats: 4, zone: 'داخلي', status: 'occupied' as const },
  { id: 'table-4', number: 4, seats: 4, zone: 'داخلي', status: 'available' as const },
  { id: 'table-5', number: 5, seats: 6, zone: 'داخلي', status: 'reserved' as const },
  { id: 'table-6', number: 6, seats: 6, zone: 'داخلي', status: 'available' as const },
  { id: 'table-7', number: 7, seats: 8, zone: 'VIP', status: 'available' as const },
  { id: 'table-8', number: 8, seats: 8, zone: 'VIP', status: 'occupied' as const },
  { id: 'table-9', number: 9, seats: 4, zone: 'تراس', status: 'available' as const },
  { id: 'table-10', number: 10, seats: 4, zone: 'تراس', status: 'available' as const },
  { id: 'table-11', number: 11, seats: 2, zone: 'تراس', status: 'occupied' as const },
  { id: 'table-12', number: 12, seats: 2, zone: 'تراس', status: 'available' as const },
];

// الطلبات الأخيرة
export const recentOrders = [
  {
    id: 'order-1',
    orderNumber: '#1234',
    type: 'dine-in' as const,
    tableNumber: 3,
    total: 485,
    status: 'preparing' as const,
    time: new Date(Date.now() - 15 * 60000),
    itemsCount: 4,
  },
  {
    id: 'order-2',
    orderNumber: '#1235',
    type: 'delivery' as const,
    customerName: 'محمد أحمد',
    total: 320,
    status: 'ready' as const,
    time: new Date(Date.now() - 8 * 60000),
    itemsCount: 3,
  },
  {
    id: 'order-3',
    orderNumber: '#1236',
    type: 'takeaway' as const,
    total: 175,
    status: 'pending' as const,
    time: new Date(Date.now() - 2 * 60000),
    itemsCount: 2,
  },
  {
    id: 'order-4',
    orderNumber: '#1237',
    type: 'dine-in' as const,
    tableNumber: 8,
    total: 890,
    status: 'completed' as const,
    time: new Date(Date.now() - 45 * 60000),
    itemsCount: 6,
  },
];

// إحصائيات لوحة التحكم
export const dashboardStats = {
  todaySales: 15420,
  ordersCount: 47,
  averageOrderValue: 328,
  pendingOrders: 8,
  preparingOrders: 12,
  completedOrders: 27,
  cancelledOrders: 0,
  tableOccupancy: 42,
  reservationsToday: 15,
  lowStockItems: 5,
  topSellingItems: [
    { name: 'كباب مشكل', count: 28, revenue: 5180 },
    { name: 'كشري مصري', count: 45, revenue: 2475 },
    { name: 'شيش طاووق', count: 22, revenue: 3190 },
    { name: 'أم علي', count: 18, revenue: 990 },
    { name: 'عصير مانجو', count: 35, revenue: 1050 },
  ],
  hourlyData: [
    { hour: '10', orders: 5, sales: 890 },
    { hour: '11', orders: 8, sales: 1420 },
    { hour: '12', orders: 15, sales: 4250 },
    { hour: '13', orders: 22, sales: 6890 },
    { hour: '14', orders: 18, sales: 5120 },
    { hour: '15', orders: 12, sales: 3450 },
    { hour: '16', orders: 8, sales: 2180 },
    { hour: '17', orders: 10, sales: 2850 },
    { hour: '18', orders: 16, sales: 4520 },
    { hour: '19', orders: 25, sales: 7890 },
    { hour: '20', orders: 28, sales: 8950 },
    { hour: '21', orders: 20, sales: 6120 },
  ],
};

// تذاكر المطبخ
export const kitchenTickets = [
  {
    id: 'ticket-1',
    orderNumber: '#1234',
    tableNumber: 3,
    items: [
      { name: 'كباب مشكل', quantity: 2, status: 'preparing' as const, notes: 'بدون بصل' },
      { name: 'أرز بالخلطة', quantity: 2, status: 'ready' as const },
      { name: 'سلطة خضراء', quantity: 2, status: 'ready' as const },
    ],
    createdAt: new Date(Date.now() - 15 * 60000),
    priority: 'normal' as const,
  },
  {
    id: 'ticket-2',
    orderNumber: '#1235',
    type: 'delivery',
    items: [
      { name: 'شيش طاووق', quantity: 1, status: 'preparing' as const },
      { name: 'حمص بالطحينة', quantity: 1, status: 'ready' as const },
      { name: 'عصير مانجو', quantity: 2, status: 'ready' as const },
    ],
    createdAt: new Date(Date.now() - 8 * 60000),
    priority: 'high' as const,
  },
  {
    id: 'ticket-3',
    orderNumber: '#1236',
    type: 'takeaway',
    items: [
      { name: 'كشري مصري', quantity: 3, status: 'pending' as const },
      { name: 'شوربة عدس', quantity: 3, status: 'pending' as const },
    ],
    createdAt: new Date(Date.now() - 2 * 60000),
    priority: 'normal' as const,
  },
];
